language: node_js

cache:
  yarn: true
  directories:
    - node_modules

dist: trusty
sudo: required

addons:
  chrome: stable

node_js:
 - "lts/*"

before_install:
 - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
 - chmod +x ./cc-test-reporter
 - ./cc-test-reporter before-build

install:
 - yarn install --production=false

before_script:
 - yarn dev

script:
 - yarn test
 - yarn prod

after_script:
 - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT